// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: auto_test_manager.proto

package web_app_sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_SUCCESS  Status = 0 // robot拉起成功
	Status_FAIL     Status = 1 // robot拉起失败
	Status_RUNNING  Status = 2 // robot运行中
	Status_DESTROY  Status = 3 // robot已销毁
	Status_CREATING Status = 4 // robot 创建中
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "RUNNING",
		3: "DESTROY",
		4: "CREATING",
	}
	Status_value = map[string]int32{
		"SUCCESS":  0,
		"FAIL":     1,
		"RUNNING":  2,
		"DESTROY":  3,
		"CREATING": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_auto_test_manager_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_auto_test_manager_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{0}
}

type ErrorMsg int32

const (
	ErrorMsg_Normal           ErrorMsg = 0
	ErrorMsg_DsVersionError   ErrorMsg = 1 // ds_version不存在或不匹配等
	ErrorMsg_GameVersionError ErrorMsg = 2 // gameVersion不存在或不匹配等
	ErrorMsg_GameIdError      ErrorMsg = 3 // gameId 不存在或不匹配等
	ErrorMsg_CreateFailed     ErrorMsg = 4 // 无法创建
	ErrorMsg_LackOfResource   ErrorMsg = 5 // 资源不足
	ErrorMsg_AgentError       ErrorMsg = 6 // 内部错误
)

// Enum value maps for ErrorMsg.
var (
	ErrorMsg_name = map[int32]string{
		0: "Normal",
		1: "DsVersionError",
		2: "GameVersionError",
		3: "GameIdError",
		4: "CreateFailed",
		5: "LackOfResource",
		6: "AgentError",
	}
	ErrorMsg_value = map[string]int32{
		"Normal":           0,
		"DsVersionError":   1,
		"GameVersionError": 2,
		"GameIdError":      3,
		"CreateFailed":     4,
		"LackOfResource":   5,
		"AgentError":       6,
	}
)

func (x ErrorMsg) Enum() *ErrorMsg {
	p := new(ErrorMsg)
	*p = x
	return p
}

func (x ErrorMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_auto_test_manager_proto_enumTypes[1].Descriptor()
}

func (ErrorMsg) Type() protoreflect.EnumType {
	return &file_auto_test_manager_proto_enumTypes[1]
}

func (x ErrorMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorMsg.Descriptor instead.
func (ErrorMsg) EnumDescriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{1}
}

type RobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotTypeId string `protobuf:"bytes,1,opt,name=robot_type_id,json=robotTypeId,proto3" json:"robot_type_id,omitempty"` // md5(ds_version+scene_id+game_version+game_id)， 表示这一类型的robot
	RobotNumber int32  `protobuf:"varint,2,opt,name=robot_number,json=robotNumber,proto3" json:"robot_number,omitempty"`  // robot 数量
	State       Status `protobuf:"varint,3,opt,name=state,proto3,enum=auto.test.manager.Status" json:"state,omitempty"`   // robot 创建状态：创建中、创建成功、已销毁、失败
}

func (x *RobotInfo) Reset() {
	*x = RobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInfo) ProtoMessage() {}

func (x *RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInfo.ProtoReflect.Descriptor instead.
func (*RobotInfo) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RobotInfo) GetRobotTypeId() string {
	if x != nil {
		return x.RobotTypeId
	}
	return ""
}

func (x *RobotInfo) GetRobotNumber() int32 {
	if x != nil {
		return x.RobotNumber
	}
	return 0
}

func (x *RobotInfo) GetState() Status {
	if x != nil {
		return x.State
	}
	return Status_SUCCESS
}

//
//- GetResourceReq： 表示auto_manager获取auto_agent上的cpu\memory\robotTypeId\robot_number等信息
type GetResourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoAgent string `protobuf:"bytes,1,opt,name=auto_agent,json=autoAgent,proto3" json:"auto_agent,omitempty"` // auto_agent服务编号
}

func (x *GetResourceReq) Reset() {
	*x = GetResourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceReq) ProtoMessage() {}

func (x *GetResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceReq.ProtoReflect.Descriptor instead.
func (*GetResourceReq) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{1}
}

func (x *GetResourceReq) GetAutoAgent() string {
	if x != nil {
		return x.AutoAgent
	}
	return ""
}

//
//- GetResourceRsp：返回auto_manager信息，auto_agent所在节点上的总cpu\memory、已使用的cpu\memory、robotTypeId和对应的robot数量等
type GetResourceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoAgent       string       `protobuf:"bytes,1,opt,name=auto_agent,json=autoAgent,proto3" json:"auto_agent,omitempty"`                    // auto_agent服务编号
	TotalCpu        int32        `protobuf:"varint,2,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"`                      // 总cpu, 默认m(1c=1000m)
	TotalMemory     int64        `protobuf:"varint,3,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`             // 总memory, 默认m (1m=1e6 bytes)
	TotalPids       int32        `protobuf:"varint,4,opt,name=total_pids,json=totalPids,proto3" json:"total_pids,omitempty"`                   // 节点进程数量限制
	AvailableCpu    int32        `protobuf:"varint,5,opt,name=available_cpu,json=availableCpu,proto3" json:"available_cpu,omitempty"`          // 可用cpu, 默认m(1c=1000m)
	AvailableMemory int64        `protobuf:"varint,6,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"` // 可用memory, 默认m (1m=1e6 bytes)
	AvailablePids   int32        `protobuf:"varint,7,opt,name=available_pids,json=availablePids,proto3" json:"available_pids,omitempty"`       // 还可创建进程数量
	RobotInfo       []*RobotInfo `protobuf:"bytes,8,rep,name=robot_info,json=robotInfo,proto3" json:"robot_info,omitempty"`                    // 所有robot类型对应的robot数量
}

func (x *GetResourceRsp) Reset() {
	*x = GetResourceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRsp) ProtoMessage() {}

func (x *GetResourceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRsp.ProtoReflect.Descriptor instead.
func (*GetResourceRsp) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceRsp) GetAutoAgent() string {
	if x != nil {
		return x.AutoAgent
	}
	return ""
}

func (x *GetResourceRsp) GetTotalCpu() int32 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

func (x *GetResourceRsp) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *GetResourceRsp) GetTotalPids() int32 {
	if x != nil {
		return x.TotalPids
	}
	return 0
}

func (x *GetResourceRsp) GetAvailableCpu() int32 {
	if x != nil {
		return x.AvailableCpu
	}
	return 0
}

func (x *GetResourceRsp) GetAvailableMemory() int64 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

func (x *GetResourceRsp) GetAvailablePids() int32 {
	if x != nil {
		return x.AvailablePids
	}
	return 0
}

func (x *GetResourceRsp) GetRobotInfo() []*RobotInfo {
	if x != nil {
		return x.RobotInfo
	}
	return nil
}

//
//- GetRobotListReq：auto_manager请求获取auto_agent服务上所有robot数据
type GetRobotListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoAgent string `protobuf:"bytes,1,opt,name=auto_agent,json=autoAgent,proto3" json:"auto_agent,omitempty"` // auto_agent服务编号
}

func (x *GetRobotListReq) Reset() {
	*x = GetRobotListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotListReq) ProtoMessage() {}

func (x *GetRobotListReq) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotListReq.ProtoReflect.Descriptor instead.
func (*GetRobotListReq) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetRobotListReq) GetAutoAgent() string {
	if x != nil {
		return x.AutoAgent
	}
	return ""
}

//
//- GetRobotListRsp：auto_agent返回所有robot类型对应的机器数量
type GetRobotListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotInfo []*RobotInfo `protobuf:"bytes,1,rep,name=robot_info,json=robotInfo,proto3" json:"robot_info,omitempty"`
}

func (x *GetRobotListRsp) Reset() {
	*x = GetRobotListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotListRsp) ProtoMessage() {}

func (x *GetRobotListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotListRsp.ProtoReflect.Descriptor instead.
func (*GetRobotListRsp) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{4}
}

func (x *GetRobotListRsp) GetRobotInfo() []*RobotInfo {
	if x != nil {
		return x.RobotInfo
	}
	return nil
}

//
//- CreateRobotReq:
//用户添加任务，当触发执行 开始\优先\重新开始 操作后，web_app_sample 根据所有的auto_agent机器资源数据，
//给出auto_agent服务应该创建的robot数量；一个任务对应一个robotTypeId，一个任务可能会被分发到1个或多个auto_agent上创建多个robot；
type CreateRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoAgent string                   `protobuf:"bytes,1,opt,name=auto_agent,json=autoAgent,proto3" json:"auto_agent,omitempty"` // auto_agent服务编号
	RobotReq  *CreateRobotReq_RobotReq `protobuf:"bytes,2,opt,name=robot_req,json=robotReq,proto3" json:"robot_req,omitempty"`    // robot创建信息
}

func (x *CreateRobotReq) Reset() {
	*x = CreateRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRobotReq) ProtoMessage() {}

func (x *CreateRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRobotReq.ProtoReflect.Descriptor instead.
func (*CreateRobotReq) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRobotReq) GetAutoAgent() string {
	if x != nil {
		return x.AutoAgent
	}
	return ""
}

func (x *CreateRobotReq) GetRobotReq() *CreateRobotReq_RobotReq {
	if x != nil {
		return x.RobotReq
	}
	return nil
}

//
//- CreateRobotRsp:
//robot_number表示auto_agent上已经成功拉起的机器数量，state取值为：success表示全部创建成功；fail表示部分创建失败或全部创建失败；
type CreateRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotTypeId string   `protobuf:"bytes,1,opt,name=robot_type_id,json=robotTypeId,proto3" json:"robot_type_id,omitempty"` // robot类型
	RobotNumber int32    `protobuf:"varint,2,opt,name=robot_number,json=robotNumber,proto3" json:"robot_number,omitempty"`  // 创建成功的机器数量
	State       Status   `protobuf:"varint,3,opt,name=state,proto3,enum=auto.test.manager.Status" json:"state,omitempty"`   // 创建状态
	Msg         ErrorMsg `protobuf:"varint,4,opt,name=msg,proto3,enum=auto.test.manager.ErrorMsg" json:"msg,omitempty"`     // 创建失败时填写对应的原因：ErrorMsg
	ErrMsg      string   `protobuf:"bytes,5,opt,name=errMsg,proto3" json:"errMsg,omitempty"`                                //错误信息描述
}

func (x *CreateRobotRsp) Reset() {
	*x = CreateRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRobotRsp) ProtoMessage() {}

func (x *CreateRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRobotRsp.ProtoReflect.Descriptor instead.
func (*CreateRobotRsp) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRobotRsp) GetRobotTypeId() string {
	if x != nil {
		return x.RobotTypeId
	}
	return ""
}

func (x *CreateRobotRsp) GetRobotNumber() int32 {
	if x != nil {
		return x.RobotNumber
	}
	return 0
}

func (x *CreateRobotRsp) GetState() Status {
	if x != nil {
		return x.State
	}
	return Status_SUCCESS
}

func (x *CreateRobotRsp) GetMsg() ErrorMsg {
	if x != nil {
		return x.Msg
	}
	return ErrorMsg_Normal
}

func (x *CreateRobotRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

//
//- DestroyRobotReq：
//传入robotTypeId，表示需要销毁auto_agent上所有的robotTypeId类型的robot
type DestroyRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoAgent string     `protobuf:"bytes,1,opt,name=auto_agent,json=autoAgent,proto3" json:"auto_agent,omitempty"` // auto_agent服务编号
	RobotReq  *RobotInfo `protobuf:"bytes,2,opt,name=robot_req,json=robotReq,proto3" json:"robot_req,omitempty"`    //
}

func (x *DestroyRobotReq) Reset() {
	*x = DestroyRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRobotReq) ProtoMessage() {}

func (x *DestroyRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRobotReq.ProtoReflect.Descriptor instead.
func (*DestroyRobotReq) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyRobotReq) GetAutoAgent() string {
	if x != nil {
		return x.AutoAgent
	}
	return ""
}

func (x *DestroyRobotReq) GetRobotReq() *RobotInfo {
	if x != nil {
		return x.RobotReq
	}
	return nil
}

//
//- DestroyRobotRsp：
//返回robotTypeId，表示auto_agent上的robotId类型已销毁的数量：只计算已经running的robot数量
type DestroyRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotRsp *RobotInfo `protobuf:"bytes,1,opt,name=robot_rsp,json=robotRsp,proto3" json:"robot_rsp,omitempty"`
}

func (x *DestroyRobotRsp) Reset() {
	*x = DestroyRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRobotRsp) ProtoMessage() {}

func (x *DestroyRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRobotRsp.ProtoReflect.Descriptor instead.
func (*DestroyRobotRsp) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyRobotRsp) GetRobotRsp() *RobotInfo {
	if x != nil {
		return x.RobotRsp
	}
	return nil
}

type StreamActiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AEvent *anypb.Any `protobuf:"bytes,1,opt,name=AEvent,proto3" json:"AEvent,omitempty"`
}

func (x *StreamActiveEvent) Reset() {
	*x = StreamActiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamActiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamActiveEvent) ProtoMessage() {}

func (x *StreamActiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamActiveEvent.ProtoReflect.Descriptor instead.
func (*StreamActiveEvent) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{9}
}

func (x *StreamActiveEvent) GetAEvent() *anypb.Any {
	if x != nil {
		return x.AEvent
	}
	return nil
}

type StreamPassiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PEvent *anypb.Any `protobuf:"bytes,1,opt,name=PEvent,proto3" json:"PEvent,omitempty"`
}

func (x *StreamPassiveEvent) Reset() {
	*x = StreamPassiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamPassiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPassiveEvent) ProtoMessage() {}

func (x *StreamPassiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPassiveEvent.ProtoReflect.Descriptor instead.
func (*StreamPassiveEvent) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{10}
}

func (x *StreamPassiveEvent) GetPEvent() *anypb.Any {
	if x != nil {
		return x.PEvent
	}
	return nil
}

type CreateRobotReq_RobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomUrl         string `protobuf:"bytes,1,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`                         // room-server服务地址
	GameId          string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                            // 游戏id
	DsVersion       string `protobuf:"bytes,3,opt,name=ds_version,json=dsVersion,proto3" json:"ds_version,omitempty"`                   // ds版本
	SceneId         string `protobuf:"bytes,4,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                         // 场景id
	GameVersion     string `protobuf:"bytes,5,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`             // 游戏版本
	RobotNumber     int32  `protobuf:"varint,6,opt,name=robot_number,json=robotNumber,proto3" json:"robot_number,omitempty"`            // 新增创建robot数量
	RobotTypeId     string `protobuf:"bytes,7,opt,name=robot_type_id,json=robotTypeId,proto3" json:"robot_type_id,omitempty"`           // md5(ds_version+scene_id+game_version+game_id)， 表示这一类型的robot
	ExtensionFields []byte `protobuf:"bytes,8,opt,name=extension_fields,json=extensionFields,proto3" json:"extension_fields,omitempty"` // 预留扩展字段
}

func (x *CreateRobotReq_RobotReq) Reset() {
	*x = CreateRobotReq_RobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auto_test_manager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRobotReq_RobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRobotReq_RobotReq) ProtoMessage() {}

func (x *CreateRobotReq_RobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_auto_test_manager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRobotReq_RobotReq.ProtoReflect.Descriptor instead.
func (*CreateRobotReq_RobotReq) Descriptor() ([]byte, []int) {
	return file_auto_test_manager_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateRobotReq_RobotReq) GetRoomUrl() string {
	if x != nil {
		return x.RoomUrl
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetDsVersion() string {
	if x != nil {
		return x.DsVersion
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetRobotNumber() int32 {
	if x != nil {
		return x.RobotNumber
	}
	return 0
}

func (x *CreateRobotReq_RobotReq) GetRobotTypeId() string {
	if x != nil {
		return x.RobotTypeId
	}
	return ""
}

func (x *CreateRobotReq_RobotReq) GetExtensionFields() []byte {
	if x != nil {
		return x.ExtensionFields
	}
	return nil
}

var File_auto_test_manager_proto protoreflect.FileDescriptor

var file_auto_test_manager_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x75, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xc2,
	0x02, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x70, 0x75, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x69, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x69, 0x64, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x70, 0x75,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x70, 0x75, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x69, 0x64,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x69, 0x64, 0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x6f,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61,
	0x75, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x88, 0x03, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75,
	0x74, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x75, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x8d, 0x02, 0x0a, 0x08, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x22, 0xcf, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x6f,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x6b, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x22,
	0x4c, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x72, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x22, 0x41, 0x0a,
	0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x41, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x42, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x69, 0x76,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x50, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x50, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2a, 0x47, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46,
	0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x10, 0x03, 0x12,
	0x0c, 0x0a, 0x08, 0x43, 0x52, 0x45, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x2a, 0x87, 0x01,
	0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x73, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x61,
	0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x61, 0x63, 0x6b, 0x4f, 0x66, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x06, 0x32, 0x6f, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x6f, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auto_test_manager_proto_rawDescOnce sync.Once
	file_auto_test_manager_proto_rawDescData = file_auto_test_manager_proto_rawDesc
)

func file_auto_test_manager_proto_rawDescGZIP() []byte {
	file_auto_test_manager_proto_rawDescOnce.Do(func() {
		file_auto_test_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_auto_test_manager_proto_rawDescData)
	})
	return file_auto_test_manager_proto_rawDescData
}

var file_auto_test_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auto_test_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auto_test_manager_proto_goTypes = []interface{}{
	(Status)(0),                     // 0: auto.test.manager.Status
	(ErrorMsg)(0),                   // 1: auto.test.manager.ErrorMsg
	(*RobotInfo)(nil),               // 2: auto.test.manager.RobotInfo
	(*GetResourceReq)(nil),          // 3: auto.test.manager.GetResourceReq
	(*GetResourceRsp)(nil),          // 4: auto.test.manager.GetResourceRsp
	(*GetRobotListReq)(nil),         // 5: auto.test.manager.GetRobotListReq
	(*GetRobotListRsp)(nil),         // 6: auto.test.manager.GetRobotListRsp
	(*CreateRobotReq)(nil),          // 7: auto.test.manager.CreateRobotReq
	(*CreateRobotRsp)(nil),          // 8: auto.test.manager.CreateRobotRsp
	(*DestroyRobotReq)(nil),         // 9: auto.test.manager.DestroyRobotReq
	(*DestroyRobotRsp)(nil),         // 10: auto.test.manager.DestroyRobotRsp
	(*StreamActiveEvent)(nil),       // 11: auto.test.manager.StreamActiveEvent
	(*StreamPassiveEvent)(nil),      // 12: auto.test.manager.StreamPassiveEvent
	(*CreateRobotReq_RobotReq)(nil), // 13: auto.test.manager.CreateRobotReq.RobotReq
	(*anypb.Any)(nil),               // 14: google.protobuf.Any
}
var file_auto_test_manager_proto_depIdxs = []int32{
	0,  // 0: auto.test.manager.RobotInfo.state:type_name -> auto.test.manager.Status
	2,  // 1: auto.test.manager.GetResourceRsp.robot_info:type_name -> auto.test.manager.RobotInfo
	2,  // 2: auto.test.manager.GetRobotListRsp.robot_info:type_name -> auto.test.manager.RobotInfo
	13, // 3: auto.test.manager.CreateRobotReq.robot_req:type_name -> auto.test.manager.CreateRobotReq.RobotReq
	0,  // 4: auto.test.manager.CreateRobotRsp.state:type_name -> auto.test.manager.Status
	1,  // 5: auto.test.manager.CreateRobotRsp.msg:type_name -> auto.test.manager.ErrorMsg
	2,  // 6: auto.test.manager.DestroyRobotReq.robot_req:type_name -> auto.test.manager.RobotInfo
	2,  // 7: auto.test.manager.DestroyRobotRsp.robot_rsp:type_name -> auto.test.manager.RobotInfo
	14, // 8: auto.test.manager.StreamActiveEvent.AEvent:type_name -> google.protobuf.Any
	14, // 9: auto.test.manager.StreamPassiveEvent.PEvent:type_name -> google.protobuf.Any
	11, // 10: auto.test.manager.AutoAgent.StreamService:input_type -> auto.test.manager.StreamActiveEvent
	12, // 11: auto.test.manager.AutoAgent.StreamService:output_type -> auto.test.manager.StreamPassiveEvent
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auto_test_manager_proto_init() }
func file_auto_test_manager_proto_init() {
	if File_auto_test_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auto_test_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamActiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamPassiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auto_test_manager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRobotReq_RobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auto_test_manager_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auto_test_manager_proto_goTypes,
		DependencyIndexes: file_auto_test_manager_proto_depIdxs,
		EnumInfos:         file_auto_test_manager_proto_enumTypes,
		MessageInfos:      file_auto_test_manager_proto_msgTypes,
	}.Build()
	File_auto_test_manager_proto = out.File
	file_auto_test_manager_proto_rawDesc = nil
	file_auto_test_manager_proto_goTypes = nil
	file_auto_test_manager_proto_depIdxs = nil
}
