apiVersion: v1
kind: Service
metadata:
  name: web-app-sample
spec:
  selector:
    app: web-app-sample
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8090
      name: httpserver
  type: ClusterIP